import Footer from './Components/Footer/Footer'
import Header from './Components/Header/Header'
import Main from './Components/Main/Main'
import ScrollLock from './Components/ScrollLock'
import './globals.css'
import { Playfair_Display } from 'next/font/google'

const  playfairDisplay =  Playfair_Display({subsets: ['latin'], weight: ['400','600', '700', '800'],style: ['normal', 'italic'], variable: "--playfairDisplay-font"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${playfairDisplay.variable}`}>
        <ScrollLock>
            <Header/>
            <Main/>
            {children}
            <Footer/>
        </ScrollLock>
    </html>
  )
}
